version: '3.7'
services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            - pokeretro-backend-incubator
    incubator-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8084:8080
        networks:
            - pokeretro-backend-incubator
            - pokeretro-backend
            - pokemon_pokeretro-backend
            - inventory_pokeretro-backend
            - team_pokeretro-backend

networks:
    pokeretro-backend-incubator:
    pokeretro-backend:
        driver: bridge
    pokemon_pokeretro-backend:
        external: true
    inventory_pokeretro-backend:
        external: true
    team_pokeretro-backend:
        external: true
