version: '3.7'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
            ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
