version: '3.7'

services:
    database:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
        networks:
            - pokeretro-backend-team
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8086:8080
        networks:
            - pokeretro-backend-team

networks:
    pokeretro-backend-team:
