db = db.getSiblingDB('team');

// Brock
db.teammates.insertMany([
    {
        _id: UUID(),
        trainerUuid: UUID('6ffe8eb1-642f-4e93-a827-0caff9af0825'),
        position: 1,
        name: 'Geodude',
        level: 1,
        xp: 0,
        baseStat: {
            hp: 40,
            attack: 80,
            defense: 100,
            speed: 20,
            special: 30,
        },
        individualStat: {
            hp: 3,
            attack: 10,
            defense: 2,
            speed: 15,
            special: 5,
        },
        effortStat: {
            hp: 0,
            attack: 0,
            defense: 0,
            speed: 0,
            special: 0,
        },
        stat: {
            hp: 14,
            attack: 12,
            defense: 13,
            speed: 7,
            special: 7,
        },
        currentStat: {
            hp: 14,
            attack: 12,
            defense: 13,
            speed: 7,
            special: 7,
        },
        capacities: [
            {
                name: 'Tackle',
                category: 'physical',
                power: 40,
                accuracy: 100,
                pp: 35,
                type: 'Normal',
                useCount: 0,
            },
        ],
        pokemon: {
            _id: 74,
            name: 'Geodude',
            types: ['Rock', 'Ground'],
        },
        _class: 'net.pokeretro.team.entity.Teammate',
    },
    {
        _id: UUID(),
        trainerUuid: UUID('6ffe8eb1-642f-4e93-a827-0caff9af0825'),
        position: 2,
        name: 'Onix',
        level: 1,
        xp: 0,
        baseStat: {
            hp: 35,
            attack: 45,
            defense: 160,
            speed: 70,
            special: 30,
        },
        individualStat: {
            hp: 1,
            attack: 0,
            defense: 14,
            speed: 14,
            special: 11,
        },
        effortStat: {
            hp: 0,
            attack: 0,
            defense: 0,
            speed: 0,
            special: 0,
        },
        stat: {
            hp: 13,
            attack: 8,
            defense: 18,
            speed: 11,
            special: 7,
        },
        currentStat: {
            hp: 13,
            attack: 8,
            defense: 18,
            speed: 11,
            special: 7,
        },
        capacities: [
            {
                name: 'Screech',
                category: 'status',
                accuracy: 85,
                pp: 40,
                type: 'Normal',
                useCount: 0,
            },
            {
                name: 'Tackle',
                category: 'physical',
                power: 40,
                accuracy: 100,
                pp: 35,
                type: 'Normal',
                useCount: 0,
            },
        ],
        pokemon: {
            _id: 95,
            name: 'Onix',
            types: ['Rock', 'Ground'],
        },
        _class: 'net.pokeretro.team.entity.Teammate',
    },
]);

// Misty
db.teammates.insertMany([
    {
        _id: UUID(),
        trainerUuid: UUID('cc652400-79c6-4c09-9271-a034582a7383'),
        position: 1,
        name: 'Staryu',
        level: 1,
        xp: 0,
        baseStat: {
            hp: 30,
            attack: 45,
            defense: 55,
            speed: 85,
            special: 70,
        },
        individualStat: {
            hp: 0,
            attack: 0,
            defense: 4,
            speed: 8,
            special: 14,
        },
        effortStat: {
            hp: 0,
            attack: 0,
            defense: 0,
            speed: 0,
            special: 0,
        },
        stat: {
            hp: 13,
            attack: 8,
            defense: 9,
            speed: 12,
            special: 10,
        },
        currentStat: {
            hp: 13,
            attack: 8,
            defense: 9,
            speed: 12,
            special: 10,
        },
        capacities: [
            {
                name: 'Tackle',
                category: 'physical',
                power: 40,
                accuracy: 100,
                pp: 35,
                type: 'Normal',
                useCount: 0,
            },
        ],
        pokemon: {
            _id: 120,
            name: 'Staryu',
            types: ['Water'],
        },
        _class: 'net.pokeretro.team.entity.Teammate',
    },
    {
        _id: UUID(),
        trainerUuid: UUID('cc652400-79c6-4c09-9271-a034582a7383'),
        position: 2,
        name: 'Starmie',
        level: 1,
        xp: 0,
        baseStat: {
            hp: 60,
            attack: 75,
            defense: 85,
            speed: 115,
            special: 100,
        },
        individualStat: {
            hp: 0,
            attack: 0,
            defense: 8,
            speed: 12,
            special: 4,
        },
        effortStat: {
            hp: 0,
            attack: 0,
            defense: 0,
            speed: 0,
            special: 0,
        },
        stat: {
            hp: 15,
            attack: 11,
            defense: 12,
            speed: 15,
            special: 13,
        },
        currentStat: {
            hp: 15,
            attack: 11,
            defense: 12,
            speed: 15,
            special: 13,
        },
        capacities: [
            {
                name: 'Harden',
                category: 'status',
                pp: 30,
                type: 'Normal',
                useCount: 0,
            },
            {
                name: 'Tackle',
                category: 'physical',
                power: 40,
                accuracy: 100,
                pp: 35,
                type: 'Normal',
                useCount: 0,
            },
            {
                name: 'Water Gun',
                category: 'special',
                power: 40,
                accuracy: 100,
                pp: 25,
                type: 'Water',
                useCount: 0,
            },
        ],
        pokemon: {
            _id: 121,
            name: 'Starmie',
            types: ['Water', 'Psychic'],
        },
        _class: 'net.pokeretro.team.entity.Teammate',
    },
]);
