version: '3.7'
services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - pokeretro-backend-trainer
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8081:8080
        networks:
            - pokeretro-backend-trainer
            - pokeretro-backend
            - pokemon_pokeretro-backend
            - team_pokeretro-backend

networks:
    pokeretro-backend-trainer:
    pokeretro-backend:
        driver: bridge
    pokemon_pokeretro-backend:
        external: true
    team_pokeretro-backend:
        external: true
