version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#  rabbitmq:
#    image: docker.io/bitnami/rabbitmq:3.11
#    ports:
#      - '4369:4369'
#      - '5551:5551'
#      - '5552:5552'
#      - '5672:5672'
#      - '25672:25672'
#      - '15672:15672'
#    environment:
#      - RABBITMQ_SECURE_PASSWORD=yes
#      - RABBITMQ_LOGS=-
#    volumes:
#      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
#volumes:
#  rabbitmq_data:
#    driver: local