version: '3.7'
services:
    database:
        image: redis
        restart: always
        networks:
            - pokeretro-backend-battle
        ports:
            - 6379:6379
#     app:
#         build:
#             context: ./
#             dockerfile: ./Dockerfile
#         restart: always
#         ports:
#             - 8085:8080
#         networks:
#             - pokeretro-backend-pokemon
networks: 
    pokeretro-backend-battle:

